### ISSUE TITLE
RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by fengyulin001** [wlr737/EMNLP2022-SEEK#7]
Hello dear author, I am running the code with this problem, I tried to change the batch_size to 8 but it didn't work. After searching online it might be the version of torch and cuda, my version is pytorch==1.11.0,cuda==11.5. but it can't solve the problem, hope I can get your help.

**Comment by wlr737** [comment]
已收到您的邮件，祝生活愉快！！

**Comment by fengyulin001** [comment]
Hello, I finally realized that it was an issue with the graphics card conflicting with the CUDA version, and my problem has been solved. Thank you very much!
